platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {'Debug' => :debug, 'Profile' => :release, 'Release' => :release}

def flutter_root
  generated = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  raise "Run flutter pub get before pod install" unless File.exist?(generated)
  File.foreach(generated) do |line|
    match = line.match(/FLUTTER_ROOT\=(.*)/)
    return match[1].strip if match
  end
  raise 'FLUTTER_ROOT missing from Generated.xcconfig'
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'ShareExtension' do
    inherit! :search_paths
    pod 'share_handler_ios_models', :path => '.symlinks/plugins/share_handler_ios/ios/Models'
  end
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each { |target| flutter_additional_ios_build_settings(target) }
end
