<script lang="ts">
  let { data, form } = $props();
  const date = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Pending';
</script>

<svelte:head><title>{data.caseRecord.title} | SAFE-ARCHIVE</title><meta name="robots" content="noindex" /></svelte:head>

<a href="/cases" class="text-sm text-slate-600 hover:underline">← Cases</a>
<div class="mt-5 flex flex-wrap items-start justify-between gap-4">
  <div><p class="text-xs font-semibold uppercase tracking-widest text-slate-500">Case {data.caseRecord.id}</p><h1 class="mt-2 text-3xl font-semibold">{data.caseRecord.title}</h1><p class="mt-2 text-sm text-slate-600">Created {date(data.caseRecord.created_at)} · <span class="capitalize">{data.caseRecord.status.replaceAll('_', ' ')}</span></p></div>
  {#if data.account.role !== 'victim'}<a href={`/api/cases/${data.caseRecord.id}/report.pdf`} class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Download PDF report</a>{/if}
</div>
{#if form?.message}<p role="alert" class="mt-5 rounded-lg bg-red-50 p-4 text-sm text-red-800">{form.message}</p>{/if}
{#if data.caseRecord.victim_statement}<section class="mt-7 rounded-xl border border-slate-200 bg-white p-6"><h2 class="font-semibold">Victim statement</h2><p class="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{data.caseRecord.victim_statement}</p></section>{/if}

<div class="mt-7 grid gap-7 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]">
  <div class="space-y-7">
    {#if data.account.role === 'victim' && ['open', 'in_review'].includes(data.caseRecord.status)}<section class="rounded-xl border border-slate-200 bg-white p-6"><h2 class="font-semibold">Add another public link</h2><form method="POST" action="?/addLink" class="mt-3 flex flex-wrap gap-2"><label class="sr-only" for="additional-url">Public URL</label><input id="additional-url" name="url" type="url" required maxlength="2048" placeholder="https://example.org/post" class="min-w-0 flex-1 rounded-md border border-slate-300 px-3 py-2 text-sm" /><button class="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Add link</button></form></section>{/if}
    <section class="rounded-xl border border-slate-200 bg-white p-6"><h2 class="text-lg font-semibold">Evidence</h2><p class="mt-1 text-sm text-slate-600">Captured public content and integrity records.</p>
      {#if data.evidence.length === 0}<p class="mt-5 text-sm text-slate-600">No evidence submitted yet.</p>{/if}
      {#each data.evidence as item}
        <article id={`evidence-${item.id}`} class="mt-5 border-t border-slate-200 pt-5">
          <div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize">{item.capture_status}</span><span class="text-xs text-slate-500">{item.platform}</span></div>
          <h3 class="mt-3 font-semibold">{item.page_title || item.original_url}</h3><a href={item.original_url} target="_blank" rel="noopener noreferrer" class="mt-1 block break-all text-sm text-blue-700 underline">{item.original_url}</a>
          <dl class="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div><dt class="text-slate-500">Capture time</dt><dd>{date(item.capture_timestamp)}</dd></div><div><dt class="text-slate-500">Author</dt><dd>{item.visible_author || 'Not identified'}</dd></div><div><dt class="text-slate-500">Visible post time</dt><dd>{item.visible_timestamp || 'Not identified'}</dd></div><div><dt class="text-slate-500">SHA-256 package hash</dt><dd class="break-all font-mono text-xs">{item.hash_sha256 || 'Pending'}</dd></div></dl>
          {#if item.capture_error}<p class="mt-4 rounded-md bg-amber-50 p-3 text-sm text-amber-900">Capture failed: {item.capture_error}</p>{/if}
          {#if item.capture_status === 'failed' && data.account.role !== 'victim'}<form method="POST" action="?/retry" class="mt-3"><input type="hidden" name="evidence_id" value={item.id} /><button class="rounded-md border border-amber-400 px-3 py-2 text-sm font-semibold">Retry capture</button></form>{/if}
          {#each data.links.filter((link) => link.evidence_id === item.id && link.shared_text) as link}<details class="mt-4"><summary class="cursor-pointer text-sm font-semibold">Text included with the shared link</summary><p class="mt-2 whitespace-pre-wrap rounded-md bg-slate-50 p-4 text-sm">{link.shared_text}</p></details>{/each}
          {#if item.visible_text}<details class="mt-4"><summary class="cursor-pointer text-sm font-semibold">Visible text</summary><p class="mt-2 max-h-72 overflow-auto whitespace-pre-wrap rounded-md bg-slate-50 p-4 text-sm">{item.visible_text}</p></details>{/if}
          {#if data.files[item.id]?.length}<div class="mt-5"><h4 class="text-sm font-semibold">Preserved files</h4><ul class="mt-2 flex flex-wrap gap-2">{#each data.files[item.id] as file}<li><a href={`/api/evidence/${item.id}/files/${file.id}`} class="inline-block rounded-md border border-slate-300 px-3 py-2 text-xs font-medium hover:bg-slate-50">Download {file.file_type.replaceAll('_', ' ')}</a></li>{/each}</ul></div>{/if}
          {#each data.files[item.id]?.filter((file) => file.file_type === 'focused_screenshot') ?? [] as screenshot}<details class="mt-4"><summary class="cursor-pointer text-sm font-semibold">View focused screenshot</summary><img src={`/api/evidence/${item.id}/files/${screenshot.id}?preview=1`} alt="Focused screenshot of the public page at capture time" loading="lazy" class="mt-3 max-h-[600px] w-full rounded-md border border-slate-200 object-contain" /></details>{/each}
          {#each data.files[item.id]?.filter((file) => file.file_type === 'full_screenshot') ?? [] as screenshot}<details class="mt-4"><summary class="cursor-pointer text-sm font-semibold">View full-page screenshot</summary><img src={`/api/evidence/${item.id}/files/${screenshot.id}?preview=1`} alt="Full-page screenshot of the public page at capture time" loading="lazy" class="mt-3 max-h-[600px] w-full rounded-md border border-slate-200 object-contain" /></details>{/each}
          {#each data.files[item.id]?.filter((file) => file.file_type === 'html') ?? [] as snapshot}<details class="mt-4"><summary class="cursor-pointer text-sm font-semibold">View captured HTML</summary><p class="mt-2 text-xs text-slate-500">Rendered in a fully sandboxed frame: no scripts run, no cookies or network access are shared with this page.</p><iframe title="Captured HTML snapshot" src={`/api/evidence/${item.id}/files/${snapshot.id}?preview=1`} sandbox="" class="mt-3 h-[500px] w-full rounded-md border border-slate-200 bg-white"></iframe></details>{/each}
          {#if data.account.role !== 'victim' && item.capture_status === 'captured' && item.visible_text}<form method="POST" action="?/analyze" class="mt-5"><input type="hidden" name="evidence_id" value={item.id} /><button class="rounded-md border border-slate-300 px-3 py-2 text-sm font-semibold hover:bg-slate-50">Run AI analysis</button><p class="mt-1 text-xs text-slate-500">Sends captured visible text to OpenAI. Results are investigator assistance, not verified facts.</p></form>{/if}
          {#each data.analyses[item.id] ?? [] as analysis}<div class="mt-5 rounded-lg border border-indigo-200 bg-indigo-50 p-4"><p class="text-xs font-semibold uppercase tracking-widest text-indigo-700">AI assistance · {date(analysis.created_at)}</p><p class="mt-2 whitespace-pre-wrap text-sm">{analysis.summary}</p><p class="mt-3 text-xs">Threats: {analysis.detected_threats.join(', ') || 'None flagged'} · Tags: {analysis.tags.join(', ') || 'None'}</p></div>{/each}
        </article>
      {/each}
    </section>
    <section class="rounded-xl border border-slate-200 bg-white p-6"><h2 class="text-lg font-semibold">Timeline</h2><ol class="mt-4 space-y-4 border-l border-slate-200 pl-5">{#each data.timeline as item}<li><p class="text-sm font-medium">{item.description}</p><p class="text-xs text-slate-500">{date(item.timestamp)}</p></li>{/each}</ol></section>
    {#if data.account.role !== 'victim'}<section class="rounded-xl border border-slate-200 bg-white p-6"><h2 class="text-lg font-semibold">Investigator notes</h2><form method="POST" action="?/note" class="mt-4"><label class="sr-only" for="note">New note</label><textarea id="note" name="body" required maxlength="10000" rows="3" class="w-full rounded-md border border-slate-300 p-3 text-sm"></textarea><button class="mt-2 rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Add note</button></form>{#each data.notes as note}<p class="mt-4 border-t border-slate-100 pt-4 text-sm"><span class="text-xs text-slate-500">{date(note.created_at)}</span><span class="mt-1 block whitespace-pre-wrap">{note.body}</span></p>{/each}</section>{/if}
  </div>
  <aside class="space-y-7">
    {#if data.caseRecord.status !== 'archived'}<section class="rounded-xl border border-slate-200 bg-white p-6"><h2 class="font-semibold">Case details</h2><form method="POST" action="?/update" class="mt-4 grid gap-3 text-sm"><label class="grid gap-1">Title<input name="title" value={data.caseRecord.title} required maxlength="200" class="rounded-md border border-slate-300 p-2" /></label>{#if data.account.role === 'victim'}<label class="grid gap-1">Statement<textarea name="victim_statement" rows="4" maxlength="4000" class="rounded-md border border-slate-300 p-2">{data.caseRecord.victim_statement ?? ''}</textarea></label>{:else}<label class="grid gap-1">Status<select name="status" class="rounded-md border border-slate-300 p-2"><option value="open" selected={data.caseRecord.status === 'open'}>Open</option><option value="in_review" selected={data.caseRecord.status === 'in_review'}>In review</option><option value="closed" selected={data.caseRecord.status === 'closed'}>Closed</option><option value="archived">Archived</option></select></label>{/if}<button class="rounded-md bg-slate-900 px-3 py-2 font-semibold text-white">Save changes</button></form></section>{/if}
    {#if data.account.role === 'administrator'}<section class="rounded-xl border border-slate-200 bg-white p-6"><h2 class="font-semibold">Assignment</h2><form method="POST" action="?/assign" class="mt-4 grid gap-3"><label class="grid gap-1 text-sm">Investigator<select name="investigator_id" class="rounded-md border border-slate-300 p-2"><option value="">Unassigned</option>{#each data.users.filter((user) => user.role === 'ngo_investigator' && user.is_active) as user}<option value={user.id} selected={data.caseRecord.assigned_investigator_id === user.id}>{user.email}</option>{/each}</select></label><button class="rounded-md bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Save assignment</button></form></section>{/if}
    {#if data.account.role !== 'victim'}<section class="rounded-xl border border-slate-200 bg-white p-6"><h2 class="font-semibold">Audit trail</h2><ul class="mt-4 space-y-3">{#each data.audit as item}<li class="border-b border-slate-100 pb-3"><p class="text-sm">{item.action.replaceAll('.', ' ')}</p><p class="text-xs text-slate-500">{date(item.timestamp)}</p></li>{/each}</ul></section>{/if}
  </aside>
</div>
